import os
import glob
from PIL import Image

# Configuration
INPUT_DIR = "raw_textures/"
OUTPUT_IMG = "romfs/atlas.png"
OUTPUT_HEADER = "source/atlas_uvs.h"
ATLAS_SIZE = 1024 # 1024x1024 is a safe maximum for 3DS

def pack_textures():
    if not os.path.exists(INPUT_DIR):
        print(f"Directory {INPUT_DIR} not found. Skipping atlas generation.")
        return

    images = glob.glob(os.path.join(INPUT_DIR, "*.png"))
    if not images:
        print(f"WARNING: No .png files found in {INPUT_DIR}! Put your individual textures here.")
        return

    atlas = Image.new("RGBA", (ATLAS_SIZE, ATLAS_SIZE), (0, 0, 0, 0))
    
    current_x = 0
    current_y = 0
    max_row_height = 0
    
    header_lines = [
        "// AUTO-GENERATED BY pack_atlas.py",
        "#pragma once",
        "",
        "struct UVData { float u, v, uw, vh; };",
        ""
    ]

    for img_path in images:
        # THE FIX: Replace spaces and dashes with underscores for C++!
        name = os.path.basename(img_path).split('.')[0].replace(" ", "_").replace("-", "_")
        img = Image.open(img_path).convert("RGBA")
        
        # Move to next row if it doesn't fit
        if current_x + img.width > ATLAS_SIZE:
            current_x = 0
            current_y += max_row_height
            max_row_height = 0
            
        if current_y + img.height > ATLAS_SIZE:
            print("ERROR: Atlas is full! Increase ATLAS_SIZE.")
            return

        # Paste image into atlas
        atlas.paste(img, (current_x, current_y))
        
        # Calculate UV coordinates (0.0 to 1.0 mapping)
        u = current_x / ATLAS_SIZE
        v = current_y / ATLAS_SIZE
        uw = img.width / ATLAS_SIZE
        vh = img.height / ATLAS_SIZE
        
        # Write to C++ header
        macro_name = f"TEX_{name.upper()}"
        header_lines.append(f"const UVData {macro_name} = {{ {u}f, {v}f, {uw}f, {vh}f }};")

        current_x += img.width
        max_row_height = max(max_row_height, img.height)

    # Save output
    os.makedirs(os.path.dirname(OUTPUT_IMG), exist_ok=True)
    atlas.save(OUTPUT_IMG)
    
    with open(OUTPUT_HEADER, "w") as f:
        f.write("\n".join(header_lines))
        
    print(f"Packed {len(images)} textures into {OUTPUT_IMG}")

if __name__ == "__main__":
    pack_textures()
