name: Build 3DS ROM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libctru libcitro3d

      - name: Compile
        run: make

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Doors-3DS-Build
          path: "*.3dsx"
